# -*- coding: UTF-8 -*-
# Copyright (C) 2009 Itaapy, ArsAperta, Pierlis, Talend

# Import from lpod
from lpod.document import odf_new_document_from_type
from lpod.document import odf_create_paragraph, odf_create_heading
from lpod.document import odf_create_style, odf_create_style_text_properties
from lpod.document import odf_create_list, odf_create_list_item
from lpod.document import odf_create_note, odf_create_annotation
from lpod.styles import rgb2hex
from lpod.xmlpart import LAST_CHILD


# Creation of the document
document = odf_new_document_from_type('text')

# Get the elements
content = document.get_xmlpart('content')
body = content.get_text_body()
styles = document.get_xmlpart('styles')
named_styles = styles.get_category_context('named')


# A paragraph with a style
heading = odf_create_heading('Heading', 1, u'A paragraph with a style')
body.insert_element(heading, LAST_CHILD)

style = odf_create_style('style1', 'paragraph')
style.set_attribute('style:parent-style-name', 'Standard')
properties = odf_create_style_text_properties()
properties.set_attribute('fo:color', rgb2hex('blue'))
properties.set_attribute('fo:background-color', rgb2hex('red'))
style.insert_element(properties, LAST_CHILD)
named_styles.insert_element(style, LAST_CHILD)

text =  u'This document has been generated by the lpOD.'
paragraph = odf_create_paragraph('style1', text)
body.insert_element(paragraph, LAST_CHILD)


# A list
heading = odf_create_heading('Heading', 1, u'A list')
body.insert_element(heading, LAST_CHILD)

my_list = odf_create_list('Standard')
for i in range(1, 4):
    item = odf_create_list_item(u'item <%d>' % i)
    my_list.insert_element(item, LAST_CHILD)
body.insert_element(my_list, LAST_CHILD)


# Footnote, endnote, annotations
heading = odf_create_heading('Heading', 1,
                             u'Footnotes, end notes, annotations')
body.insert_element(heading, LAST_CHILD)

text1 = u'A paragraph with a footnote.'
text2 = u'A paragraph with an end note.'
text3 = u'A paragraph with an annotation.'

offset = len(u'A paragraph')

footnote = odf_create_note(u'1 ', id='note1', body=u'A footnote')
paragraph = odf_create_paragraph('Standard', text1)
paragraph.wrap_text(footnote, offset=offset)
body.insert_element(paragraph, LAST_CHILD)

endnote = odf_create_note(u'i ', note_class='endnote', id='note1',
                          body=u'An end note')
paragraph = odf_create_paragraph('Standard', text2)
paragraph.wrap_text(endnote, offset=offset)
body.insert_element(paragraph, LAST_CHILD)

annotation = odf_create_annotation(u'Anonymous', u'An annotation')
paragraph = odf_create_paragraph('Standard', text3)
paragraph.wrap_text(annotation, offset=offset)
body.insert_element(paragraph, LAST_CHILD)


# Save
document.save('basic-text.odt', pretty=True)


